name: Lab3 Kubernetes Quality Gate

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  k8s-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create KinD cluster
        uses: helm/kind-action@v1.10.0

      - name: Check cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Wait for pods to be ready
        run: |
          kubectl get pods -A
          kubectl wait --for=condition=ready pod -l app=ecommerce-app --timeout=120s

      - name: Run Grading Script
        run: |
          chmod +x ./tests/lab3_test.sh
          ./tests/lab3_test.sh
